In [23]:
## Module

from PIL import Image
import torchvision.transforms as transforms

In [24]:
imgcat = '../../datas/smudgeyyy.jpg'

In [25]:
cat = Image.open(fp = imgcat)
cat.format, cat.height, cat.width, cat.mode, type(cat)

('JPEG', 608, 1080, 'RGB', PIL.JpegImagePlugin.JpegImageFile)

In [26]:
# 이미지 텐서화

totensor = transforms.ToTensor() #labelencoder처럼.... 인스턴스 만들고 집어넣기
catTs = totensor(cat)

In [27]:
#변환된 이미지 텐서 확인
print(catTs.shape, catTs.ndim)
print(catTs[0])

torch.Size([3, 608, 1080]) 3
tensor([[0.8980, 0.8980, 0.8980,  ..., 0.1020, 0.1020, 0.1020],
        [0.9059, 0.9059, 0.9059,  ..., 0.1020, 0.1020, 0.1020],
        [0.9137, 0.9137, 0.9137,  ..., 0.0980, 0.1020, 0.1020],
        ...,
        [0.5373, 0.5333, 0.5294,  ..., 0.8941, 0.8941, 0.8941],
        [0.5294, 0.5294, 0.5294,  ..., 0.8941, 0.8941, 0.8941],
        [0.5216, 0.5294, 0.5333,  ..., 0.8902, 0.8941, 0.8941]])


In [31]:
#### OPEN CV
import cv2
img = cv2.imread(filename=imgcat) #BGR
img2 = cv2.cvtColor(src=img, code=cv2.COLOR_BGR2RGB) #RGB
type(img)

#tensorize
cat2 = totensor(img)
cat3 = totensor(img2)
print(cat2.shape, cat2.ndim, cat2[0], sep='\n\n')
print(cat3.shape, cat3.ndim, cat3[0], sep='\n\n')

torch.Size([3, 608, 1080])

3

tensor([[0.8902, 0.8902, 0.8902,  ..., 0.1059, 0.1059, 0.1059],
        [0.8980, 0.8980, 0.8980,  ..., 0.1059, 0.1059, 0.1059],
        [0.9059, 0.9059, 0.9059,  ..., 0.1020, 0.1059, 0.1059],
        ...,
        [0.4941, 0.4902, 0.4863,  ..., 0.7882, 0.7882, 0.7882],
        [0.4863, 0.4863, 0.4863,  ..., 0.7882, 0.7882, 0.7882],
        [0.4784, 0.4863, 0.4902,  ..., 0.7843, 0.7882, 0.7882]])
torch.Size([3, 608, 1080])

3

tensor([[0.8980, 0.8980, 0.8980,  ..., 0.1020, 0.1020, 0.1020],
        [0.9059, 0.9059, 0.9059,  ..., 0.1020, 0.1020, 0.1020],
        [0.9137, 0.9137, 0.9137,  ..., 0.0980, 0.1020, 0.1020],
        ...,
        [0.5373, 0.5333, 0.5294,  ..., 0.8941, 0.8941, 0.8941],
        [0.5294, 0.5294, 0.5294,  ..., 0.8941, 0.8941, 0.8941],
        [0.5216, 0.5294, 0.5333,  ..., 0.8902, 0.8941, 0.8941]])


In [35]:
### resizing
preprocessing = transforms.Compose(
    [transforms.Resize(size=(50,50)), # 넘파이 안됨..
    transforms.ToTensor()]
    )

In [45]:
preprocessing(cat)

tensor([[[0.9137, 0.9137, 0.9098,  ..., 0.0941, 0.0980, 0.0980],
         [0.9216, 0.9176, 0.9137,  ..., 0.0980, 0.0980, 0.0980],
         [0.9176, 0.9176, 0.9137,  ..., 0.0980, 0.0980, 0.0980],
         ...,
         [0.3843, 0.4353, 0.4353,  ..., 0.2667, 0.6000, 0.8745],
         [0.4902, 0.5529, 0.4745,  ..., 0.6039, 0.6706, 0.8745],
         [0.5647, 0.5020, 0.4471,  ..., 0.5059, 0.4549, 0.8510]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.0706, 0.0745, 0.0784],
         [0.9216, 0.9176, 0.9137,  ..., 0.0745, 0.0745, 0.0745],
         [0.9176, 0.9176, 0.9176,  ..., 0.0745, 0.0706, 0.0745],
         ...,
         [0.3922, 0.4392, 0.4392,  ..., 0.2510, 0.5961, 0.8549],
         [0.5020, 0.5608, 0.4706,  ..., 0.6471, 0.6706, 0.8275],
         [0.5804, 0.5137, 0.4471,  ..., 0.5373, 0.4275, 0.7922]],

        [[0.9059, 0.9059, 0.9020,  ..., 0.0980, 0.1020, 0.1059],
         [0.9176, 0.9137, 0.8941,  ..., 0.1059, 0.1020, 0.1059],
         [0.9176, 0.9020, 0.8941,  ..., 0.1020, 0.1020, 0.

### 이미지 데이터셋 <hr>
- torchvision.ImageFolder 클래스 사용
    - 이미지 데이터 라벨링
    - 이미지 데이터 전처리
        

In [46]:
from torchvision.datasets import ImageFolder

In [47]:
imgroot = '../../../datas/Project Jellyfish'
imgdataset = ImageFolder(root=imgroot
                  , transform=preprocessing)

In [48]:
# 폴더명이 분류 클래스
imgdataset.classes, imgdataset.class_to_idx, imgdataset.imgs

(['Moon_jellyfish',
  'Train_Test_Valid',
  'barrel_jellyfish',
  'blue_jellyfish',
  'compass_jellyfish',
  'lions_mane_jellyfish',
  'mauve_stinger_jellyfish'],
 {'Moon_jellyfish': 0,
  'Train_Test_Valid': 1,
  'barrel_jellyfish': 2,
  'blue_jellyfish': 3,
  'compass_jellyfish': 4,
  'lions_mane_jellyfish': 5,
  'mauve_stinger_jellyfish': 6},
 [('../../../datas/Project Jellyfish\\Moon_jellyfish\\01.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\02.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\03.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\04.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\05.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\06.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\08.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\10.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfish\\12.jpg', 0),
  ('../../../datas/Project Jellyfish\\Moon_jellyfi

In [49]:
# 데이터 로드
from torch.utils.data import DataLoader
imgdl = DataLoader(dataset= imgdataset)

In [50]:
for (img, label) in imgdl:
    print(img.shape, label.shape)
    break

torch.Size([1, 3, 50, 50]) torch.Size([1])
