### [기본적 이미지 다루기]

In [6]:
#MODULE
import cv2
import numpy as np

- [ 1 ] image data load
    - color / grayscale image converted load available

In [7]:
file = '../datas/KakaoTalk_20240322_100801555.png'

In [8]:
# COLOR IMAGE LOAD(default)
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

#GRAY IMAGE LOAD
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

In [9]:
#Image data info check

print(f'[COLOR IMG]')
print(f'SHAPE: {img_rgb.shape}\nDIM:{img_rgb.ndim}D')
print(f'TYPE: {img_rgb.dtype}\nSIZE:{img_rgb.size}bytes\n\n')

#Gray Image data info check: size = color img * 1/3
print(f'[GRAYSCALED IMG]')
print(f'SHAPE: {img_gray.shape}\nDIM:{img_gray.ndim}D')
print(f'TYPE: {img_gray.dtype}\nSIZE:{img_gray.size}bytes')
#shape: Height, Width, Channel 순으로 출력

[COLOR IMG]
SHAPE: (565, 603, 3)
DIM:3D
TYPE: uint8
SIZE:1022085bytes


[GRAYSCALED IMG]
SHAPE: (565, 603)
DIM:2D
TYPE: uint8
SIZE:340695bytes


In [10]:
### IMAGE WINDOW SHOW

cv2.imshow('[COLOR]', img_rgb)

#IMAGE WINDOW CONTROL CODE
cv2.waitKey()

##CLOSE IMAGE WINDOW
cv2.destroyAllWindows()

In [11]:
imgfile = '../../datas/Project Jellyfish/Moon_jellyfish/01.jpg'
img = cv2.imread(imgfile)

if img is not None:
    cv2.imshow('MOON_JELLYFISH',img)
    cv2.waitKey()
    cv2.destroyAllWindows()
    
else:
    print('THERE IS NO IMG FILE')

In [12]:
img_grayjf = cv2.imread(imgfile, cv2.IMREAD_GRAYSCALE)
savefilename = '../datas/grayjellyfish.jpg'
grayjellyfish = cv2.imwrite(savefilename,img_gray)

In [13]:
img = cv2.imread(imgfile)

img_b, img_g, img_r = cv2.split(img)#이미지 채널로 분리하기 (bgr)
#b,g,r = img[:,:,0], img[:,:,1], img[:,:,2] <- ndarray로 분리하기

cv2.imshow('[B]', img_b)
cv2.imshow('[G]', img_g)
cv2.imshow('[R]', img_r)


cv2.waitKey(delay= 8000)
cv2.destroyAllWindows()

In [14]:
 # 이미지데이터 채널 병합 / 변경하기
img_rgb = cv2.merge((img_r, img_g, img_b))
 #BGR to RGB
cv2.imshow('[RGB]',img_rgb)
cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
#RGB -> HSV

# img_hsv = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2HSV)
# planes = cv2.split(img_hsv)
# 
# cv2.imshow('[HSV]', planes)
# 
# cv2.waitKey()
# cv2.destroyAllWindows()

In [16]:
# 이미지 창 띄우기
cv2.imshow('[color]', img)


#IMAGE WINDOW CONTROL CODE
if cv2.waitKey() or cv2.getWindowProperty('[color]', cv2.WND_PROP_VISIBLE)<1:
    cv2.destroyAllWindows()

In [17]:
#Image Resizing

downimg = cv2.resize(img, dsize=(30,30), interpolation=cv2.INTER_AREA)
upimg = cv2.resize(img, dsize=(0,0), fx=1.5, fy = 1.5, interpolation=cv2.INTER_CUBIC)

# cv2. imshow('[down]', downimg)
# cv2.imshow('[up]', upimg)
# cv2.imshow(['org', img])
# 
# cv2.waitKey()
# cv2.destroyAllWindows()

In [23]:
# 도화지 만들기

import numpy as np
blksketchbook = np.zeros((100,100))
blksketchbook.shape, blksketchbook.ndim

wtesketchbook = np.full((300,300),255, dtype=np.uint8)

In [26]:
# 도화지에 그림 그리기
cv2.line(blksketchbook, (10, 10), (70,70), (255,255,0),10)
print(blksketchbook)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [27]:
#출력하기
cv2.imshow('BLK',blksketchbook)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [31]:
white = np.full((500,500,3),255,dtype=np.uint8)

cv2.line(white, (50,50),(150,50),(255,0,0))
cv2.line(white, (200,50), (300,50), (0,255,0))
cv2.line(white, (350,50),(450,50), (0,0,255))

#하늘색 10픽셀 선
cv2.line(white,(100,100), (400,100),(255,255,0),10)
cv2.line(white,(100,150),(400,150),(255,0,255),10)
cv2.line(white,(100,200),(400,200),(0,255,255),10)
cv2.line(white,(100,250),(400,250),(200,200,200),10)
cv2.line(img,(100,300),(400,300),(0,0,0),10)

#4d연결 선
cv2.line(white,(100,350),(400,400),(0,0,255),20,cv2.LINE_4)
cv2.line(white,(100,400),(400,450),(0,0,255),20, cv2.LINE_8)
cv2.line(white,(100,450),(400,500),(0,0,255),20, cv2.LINE_AA)

#이미지 전체에 대각선
cv2.line(white,(0,0),(500,500),(0,0,255))

cv2.imshow('WHITE',white)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
cv2.rectangle(img,(50,50),(150,150),(255,0,0)) #img 이미지에 좌상 50, 50, 우하 150,150좌표에다 네모 그려줘
cv2.rectangle(img,(300,300),(100,100),(0,255,0),10)
cv2.rectangle(img,(450,200),(200,450),(0,0,255),-1) #사각형 채워서 그리기

cv2.imshow('RECT',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [33]:

# 번개모양 선
pts1 = np.array([[50,50],[150,150],[100,140],[200,240]],dtype=np.int32)
#세모
pts2 = np.array([[350,50],[250,200],[450,200],] ,dtype = np.int32)
#세모
pts3 = np.array([[150,300],[50,450],[250,450]],dtype=np.int32)

# 오각형
pts4 = np.array([[350,250],[450,350],[400,450],[300,450],[250,350]],dtype = np.int32)

#다각형 그리기
cv2.polylines(white, [pts1], False,(255,0,0))
cv2.polylines(white, [pts2], False,(0,0,0),10)
cv2.polylines(white,[pts3], True, (0,0,0))
cv2.polylines(white,[pts4], True, (0,0,0))

cv2.imshow('polylines',white)
cv2.waitKey()
cv2.destroyAllWindows()

In [34]:
white = np.ndarray ((500,500,3),dtype=np.uint8)
white.fill(255)

In [35]:
# 원 그리기

#원 중심(150,150), 반지름 100
cv2.circle(white, (150, 150),100,(255,0,0))
cv2.circle(white, (300,150), 70, (0,255,0),5)

#원 중심(400,150), 반지름 50, 컬러 0,0,255, 채우기
cv2.circle(white,(400,150),50,(0,0,255),-1)

# 호 그리기(0도부터 360도)
cv2.ellipse(white,(50,300),(50,50),0,0,360,(0,0,255))

#반원 그리기
cv2.ellipse(white,(150,300),(50,50),0,0,180,(255,0,0))
cv2.ellipse(white,(200,300),(50,50),0,181,360,(0,0,255))

# 타원 그리기
cv2.ellipse(white, (325,300),(75,50),0,0,360,(0,255,0))
cv2.ellipse(white,(200,425),(50,75),45,0,360,(255,0,255))

# 회전 호 그리기
cv2.ellipse(white,(50,425),(50,75),45,0,360,(0,0,0))
cv2.ellipse(white,(200,425),(50,75),0,0,360,(0,0,0))

#타원 호
cv2.ellipse(white,(350,425),(50,75),45,0,180,(0,0,255))
cv2.ellipse(white,(400,425),(50,75),45,181,360,(255,0,0))

cv2.imshow('ellipse',white)
cv2.waitKey()
cv2.destroyAllWindows()

In [36]:
white = np.ndarray ((500,500,3),dtype=np.uint8)

In [37]:
#글씨 쓰기
cv2.putText(white,"Plain",(50,30),cv2.FONT_HERSHEY_PLAIN,1,(0,0,0))
cv2.putText(white,"Simplex",(50,30),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0))
cv2.putText(white,"Duplex",(50,110),cv2.FONT_HERSHEY_DUPLEX,1,(0,0,0))

#2개
cv2.putText(white,'Simplex', (200,110),cv2.FONT_HERSHEY_SIMPLEX,2,(0,0,250))

cv2.putText(white,"Complex Small", (50,180),cv2.FONT_HERSHEY_COMPLEX_SMALL,1,(0,0,0))
cv2.putText(white,"Complex",(50,220),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,0))
cv2.putText(white,"TRiplex",(50,260),cv2.FONT_HERSHEY_TRIPLEX,1,(0,0,0))

cv2.putText(white, "complex",(200,260), cv2.FONT_HERSHEY_TRIPLEX,2,(0,0,255))
cv2.putText(white,"script simplex",(50,330),cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,1,(0,0,0))
cv2.putText(white,"script complex",(50,370),cv2.FONT_HERSHEY_SCRIPT_COMPLEX,1,(0,0,0))

#italic

cv2.putText(white,"plain italic",(50,430),cv2.FONT_HERSHEY_PLAIN|cv2.FONT_ITALIC,1,(0,0,0))
cv2.putText(white,"simple italic",(50,470),cv2.FONT_HERSHEY_COMPLEX|cv2.FONT_ITALIC,1,(0,0,0))

cv2.imshow('drqwtext',white)
cv2.waitKey()
cv2.destroyAllWindows()

In [40]:
frontalface_model = '../datas/hrc/haarcascade_frontalface_alt.xml'
imgfile = '../datas/aha.jpg'

#정변얼굴 인식 모델 로딩
face_detector = cv2.CascadeClassifier(frontalface_model)

#이미지 로딩
imgNP = cv2.imread(imgfile)

#이미지 정면 얼굴 인식-> (결과) 인식된 얼굴 수만큼 위치정보(x,y,w,h) 반환
facedetections = face_detector.detectMultiScale(imgNP)
print(f'**face_detections RESULT\n{facedetections}')

#인식된 정면 얼굴 ROI 표시
for x,y,w,h in facedetections:
    cv2.rectangle(imgNP,(x,y),(x+w,y+h),(0,255,0),2)
    
#표시된 이미지 출력
cv2.imshow('[M]',imgNP)

#키 입력하면 창 닫기
if cv2.waitKey()or cv2.getWindowProperty('image',cv2.WND_PROP_VISIBLE)<1:
    cv2.destroyAllWindows()

**face_detections RESULT
[[51 32 96 96]]
