In [1]:
## Module Loading
import numpy as np

In [2]:
#ndarray type data 

# array data full of 0: zeros()
np.zeros(2)

array([0., 0.])

In [4]:
np.zeros((2,3), dtype=np.int8) #2행 3열

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [7]:
#array data full of 1: ones(rows, cols)
np.ones((2,3)),#default dtype = float64
np.ones(10, dtype=np.int32), np.ones((2,5), dtype=np.bool_) #ones, 1 = True

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [8]:
# 랜덤 데이터로 ndarray 생성
np.random.randint(1,5,size = (,3,10)) #1 ~ 4를 가지고 3행 10열 만들기

array([[1, 3, 3, 2, 2, 1, 2, 3, 1, 2],
       [1, 4, 1, 4, 3, 3, 1, 2, 4, 1],
       [2, 1, 4, 1, 4, 3, 1, 3, 4, 1]])

In [10]:
# 0 ≤ value < 1 사이 값 생성
np.random.rand(2) , np.random.rand(1,3)

(array([0.41535579, 0.62180118]),
 array([[0.00596271, 0.40825902, 0.78294849]]))

In [12]:
#정규분포를 따르는..
np.random.randn(5), np.random.randn(1,2,3)

(array([-0.27208985,  2.86762912,  1.86682107, -1.38094488,  0.95489371]),
 array([[[-0.90063734, -1.49270662,  1.18301827],
         [-0.35167058,  0.37518368, -0.45455982]]]))

In [14]:
# random 고정
np.random.seed(4)
np.random.randn(5)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [17]:
data = np.random.randn(10)
print (f' [ORIGINAL] : {data}')
np.random.shuffle(data)
print(f' [SHUFFLED] : {data}')

 [ORIGINAL] : [ 0.96462482 -0.18060193 -0.30466772  0.68853327 -0.58434414  0.33244159
  0.13800229  0.75509424 -0.36990224 -0.99204471]
 [SHUFFLED] : [-0.18060193 -0.36990224  0.75509424  0.96462482 -0.99204471  0.68853327
 -0.30466772  0.13800229 -0.58434414  0.33244159]


In [18]:
data.sum(), data.max(), data.min()

(0.44713547349099103, 0.9646248225456242, -0.9920447055886228)

In [19]:
data.argmax()

3

In [20]:
data.argmin()

4