In [61]:
import numpy as np

In [62]:
# 객체 생성
ar1 = np.array(5)
ar2 = np. array([12,3])
ar3 = np.array([[1,2,3],[4,5,6]],dtype=int)

print(ar1, ar2, ar3, sep='\n\n')

5

[12  3]

[[1 2 3]
 [4 5 6]]


In [63]:
#속성 프린트하기
def printAttribute(obj, strobj):
    print(f'======= {strobj} Attribute =======')
    print(f'DEMENSION: {obj.ndim}')
    print(f'SHAPE: {obj.shape}')
    print(f'DTYPE: {obj.dtype}')
    print(f'SIZE: {obj.size}')
    print(f'ITEM SIZE: {obj.itemsize}')
    print(f'DATA: {obj.data}')

In [64]:
printAttribute(ar1,'ar3')

======= ar3 Attribute =======
DEMENSION: 0
SHAPE: ()
DTYPE: int32
SIZE: 1
ITEM SIZE: 4
DATA: <memory at 0x0000027121B139A0>


In [65]:
#메서드 알아보기
def runAM(obj):
    print(f'[Obj.MAX]: {obj.max()}')
    print(f'[Obj.MIN]: {obj.min()}')
    print(f'[OBJ.SUM]: {obj.sum()}')
    print(f'[OBJ.CUMULATIVE SUM]: {obj.cumsum()}',sep='\n')
    print(f'[OBJ.MEAN]: {obj.mean()}')
    if obj.ndim>=2:
        print(f'[OBJ.MAX(axis=0)]: {obj.max(axis=0)}')
        print(f'[OBJ.MAX(axis=1)]: {obj.max(axis=1)}')
        print(f'[OBJ.SUM(axis=0)]: {obj.sum(axis=0)}')
        print(f'[OBJ.SUM(axis=1)]: {obj.sum(axis=1)}')
        print(f'[OBJ.MEAN(axis=0)]: {obj.mean(axis=0)}')
        print(f'[OBJ.MEAN(acis=1]: {obj.mean(axis=1)}')

In [66]:
runAM(ar3)

[Obj.MAX]: 6
[Obj.MIN]: 1
[OBJ.SUM]: 21
[OBJ.CUMULATIVE SUM]: [ 1  3  6 10 15 21]
[OBJ.MEAN]: 3.5
[OBJ.MAX(axis=0)]: [4 5 6]
[OBJ.MAX(axis=1)]: [3 6]
[OBJ.SUM(axis=0)]: [5 7 9]
[OBJ.SUM(axis=1)]: [ 6 15]
[OBJ.MEAN(axis=0)]: [2.5 3.5 4.5]
[OBJ.MEAN(acis=1]: [2. 5.]


In [67]:
# 1로만 채운 ndarray 생성하기
arr1 = np.ones(5)
arr2 = np.ones((3,))
arr3 = np.ones((2,3))
arr4 = np.ones((2,2),dtype=int)

In [68]:
runAM(arr4)

[Obj.MAX]: 1
[Obj.MIN]: 1
[OBJ.SUM]: 4
[OBJ.CUMULATIVE SUM]: [1 2 3 4]
[OBJ.MEAN]: 1.0
[OBJ.MAX(axis=0)]: [1 1]
[OBJ.MAX(axis=1)]: [1 1]
[OBJ.SUM(axis=0)]: [2 2]
[OBJ.SUM(axis=1)]: [2 2]
[OBJ.MEAN(axis=0)]: [1. 1.]
[OBJ.MEAN(acis=1]: [1. 1.]


In [69]:
#0으로만 채운 ndarray 생성하기
arr0_1 = np.zeros(5)
arr0_2 = np.zeros((5,)) #얘 왜 1차원이지?
arr0_3 = np.zeros((3,3),dtype=int)

In [70]:
arr0_1, arr0_2.dtype, arr0_3

(array([0., 0., 0., 0., 0.]),
 dtype('float64'),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [71]:
# 대각선으로 1, 나머지 0으로 채우는 객체 생성

arreye1 = np.eye(2)
arreye2 = np.eye(2,3)
arreye3 = np.eye(2,k=1) #k = 주대각선(1이 채워지는 위치)을 오른쪽 아래로 한 칸 이동한다.

In [72]:
print(arreye1, arreye2, arreye3, sep='\n\n')

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[0. 1.]
 [0. 0.]]


In [73]:
# 빈 ndarray 객체 생성
emptyarr1 = np.empty(2)
emptyarr2 = np.empty((2,),dtype=np.float16)
emptyarr3 = np.empty((2,3),dtype=np.int64)

In [74]:
print(emptyarr1, emptyarr2,emptyarr3, sep='\n\n')

[1. 1.]

[0.000015 0.      ]

[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]]


In [75]:
# 입력 배열의 shape만 복사하고 모든 원소를 1로 초기화하는 객체

onelike1 = np.array([[11,11],[22,22],[33,33]])
onelike2 = np.ones_like(onelike1)

In [76]:
print(onelike1, onelike2, sep='\n\n')

[[11 11]
 [22 22]
 [33 33]]

[[1 1]
 [1 1]
 [1 1]]


In [77]:
#arange: 범위를 나타내는 숫자열을 ndarray로 반환하는 객체

arrng1 = np.arange(10)
arrng2 = np.arange(1,10)
arrng3 = np.arange(1,10,3, dtype=np.float32)

In [78]:
arrng1,arrng2, arrng3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1., 4., 7.], dtype=float32))

In [79]:
# 주어진 범위 내에서 균등한 간격으로 일정 개수의 숫자를 포함하는 배열 생성하기
lin1 = np.linspace(2,3,num =3)
lin2 = np.linspace(1,5, num= 5)
lin3 = np.linspace(1,5, num = 5, endpoint= False) #stop 값 포함하지 않음
lin4 = np.linspace(1,5, num= 5, retstep= True) #배열과 스텝 값 반환함

In [80]:
print(lin1, lin2, lin3, lin4, sep='\n\n')

[2.  2.5 3. ]

[1. 2. 3. 4. 5.]

[1.  1.8 2.6 3.4 4.2]

(array([1., 2., 3., 4., 5.]), 1.0)


In [81]:
# 로그스케일 숫자 배열 생성하기
np.set_printoptions(precision=6, suppress=True)

log1 = np.logspace(2,3,num = 2)
log2 = np.logspace(1,5, num=5, base=2)
log3 = np.logspace(1,3, num = 3, endpoint=False)
log4 = np.logspace(1,3, num = 3, endpoint=True)

In [82]:
log1, log2, log3, log4

(array([ 100., 1000.]),
 array([ 2.,  4.,  8., 16., 32.]),
 array([ 10.      ,  46.415888, 215.443469]),
 array([  10.,  100., 1000.]))

### ndarray 객체 shape 변환하기

In [83]:
# ndarray 객체 생성
arr01 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('[arr01.shape]:',arr01.shape, '\n', arr01)
print('\n\n')
arr01 = arr01.T #행렬 전치: 열을 행으로, 행을 열로 전환
print('[arr01.T.shape]:',arr01.T.shape, '\n', arr01.T)

[arr01.shape]: (2, 5) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]



[arr01.T.shape]: (2, 5) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## ndarray 객체 shape, size(원소 수) 변환하기

In [84]:
#size 변환
np.resize(arr01, (5,2)) # 5행 2열로 변환하여 복사본 반환
arr01.resize((5,2), refcheck=True) # 원본 ndarray에 변경 적용하기

## Boolean Indexing

In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Joe'])

name1 = names == 'Bob'
name2 = names != 'Bob'
name3 = ~(names =='Bob')
name4 = (names=='Bob')|(names == 'Joe')#%%
 #or
name5 = (names=='Bob')&(names == 'Joe') #and


In [86]:
#ndarray object create-----------------

data = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

#3,4,5 추출을 위한 마스크 생성 & 적용

mask = (data>2)&(data<6)
print(mask)
print(data[mask])

[[False False False]
 [ True  True  True]
 [False False False]
 [False False False]]
[3 4 5]


In [87]:
# 3,4,5 데이터를 제외한 나머지 데이터 추출을 위한 마스크 생성 & 적용

mask2 = ~((data>2)&(data<6)) #~: not~
print(mask2)
print(data[mask2])

[[ True  True  True]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 0  1  2  6  7  8  9 10 11]


### 행, 열, 요소 삭제하기

In [88]:
#요소 삭제: 1D array 반환
np.delete(data, 2) #data array의 2번째 요소 삭제
np.delete(data, [2,3,4,5,6]) #data array의 2~6번째 요소 삭제

array([ 0,  1,  7,  8,  9, 10, 11])

In [89]:
# 행 삭제
np.delete(data,1, axis = 0)#data array 1번째 행(axis = 0) 삭제

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
# 열 삭제
np.delete(data,1, axis = 1) #data array 1번째 열(axis = 1) 삭제

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

## 행, 열, 요소 추가하기: append

In [91]:
#요소 추가하기
np.append(data,[11,12,13])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11, 12, 13])

In [92]:
# 행 추가하기

np.append(data, [[12,13,14]], axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
# 행 추가하기
np.append(data, [[12,13,14]], axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [105]:
# # 열 추가하기
np.append(data,[[4,5,6]], axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 1

## 행, 열, 요소 삽입하기

In [98]:
# 요소 삽입
np. insert(data, 2, 5)

array([ 0,  1,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
#행 삽입
np.insert(data,2,[5,6,7], axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [101]:
# 열 삽입
np.insert(data,2,[7,8,9,10], axis = 1)

array([[ 0,  1,  7,  2],
       [ 3,  4,  8,  5],
       [ 6,  7,  9,  8],
       [ 9, 10, 10, 11]])

## 합치기 / 연결: 2개 이상의 배열
- np. concatenate((arr1, arr2), axis): 축 기준 결합
- 기준 축 제외 나머지 shape 동일할 것

In [109]:
data1 = np.random.randint(1,20,(5,5))
data2 = np.random.randint(1,20,(5,5))
data1.shape, data1.ndim, data1

((5, 5),
 2,
 array([[14, 19,  7, 17, 17],
        [12, 17,  3,  6, 12],
        [15,  1,  3, 13,  4],
        [11, 14, 18, 12,  6],
        [ 1,  3, 19, 19, 11]]))

In [110]:
# [Default] 행 방향
data3 = np.concatenate((data1,data2))

In [111]:
#[Option] 열 방향
data4 = np.concatenate((data1,data2), axis = 1)

In [112]:
#[Option2] 1D
data5 = np.concatenate((data1, data2), axis = None)